build:
  image: ensime/ensime:v2.x
  pull: true
  environment:
    - SONATYPE_USERNAME=$$SONATYPE_USERNAME
    - SONATYPE_PASSWORD=$$SONATYPE_PASSWORD
  commands:
    - host `curl -s http://httpbin.org/ip | jq -r '.origin'` || true ;
    - git log | head -n 20
    - sbt test
    - if [ -z "$CI_PULL_REQUEST" ] ; then
        sbt publish ;
        sbt assembly ;
      fi

# deploy:
#   sftp:
#     host: docs.typelevel.org
#     username: typelevel
#     destination_path: ensime.typelevel.org/
#     files: 
#       - target/scala-2.10/*-assembly.jar
