language: java
os:
  - osx
branches:
  only:
    - master
script:
  - curl https://raw.githubusercontent.com/paulp/sbt-extras/master/sbt -o sbt ; chmod 755 sbt
  - ./sbt assembly test scripted
  - git clone --depth 1 --branch 1.0 https://github.com/ensime/ensime-server.git &&
    echo -javaagent:`find $PWD/target -name '*assembly.jar' -print` >> ensime-server/.jvmopts &&
    cd ensime-server &&
    echo "sbt.version=0.13.13" > project/build.properties &&
    ../sbt test:compile it:compile
cache:
  directories:
  - $HOME/.sbt
  - $HOME/.ivy2
  - $HOME/.coursier
notifications:
  email: false
