install:
  - ps: |
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      if (!(Test-Path -Path "C:\sbt" )) {
        (new-object System.Net.WebClient).DownloadFile(
          'https://dl.bintray.com/sbt/native-packages/sbt/0.13.11/sbt-0.13.11.zip',
          'C:\sbt-bin.zip'
        )
        [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\sbt-bin.zip", "C:\sbt")
      }
  - cmd: SET JAVA_HOME=C:\Program Files\Java\jdk1.7.0
  - cmd: SET PATH=C:\sbt\sbt\bin;%JAVA_HOME%\bin;%PATH%
  - cmd: SET SBT_OPTS=-XX:MaxPermSize=256m -Xss2m -Xms512m -Xmx512m
  - cmd: SET AKKA_TEST_TIMEFACTOR=10
  - cmd: SET SBT_TASK_LIMIT=2
  - cmd: git config core.symlinks true
  - cmd: git reset --hard
build_script:
  - sbt assembly test scripted
  - ps: |
      $CLASS_MONKEY = Get-ChildItem -Path target -Filter *-assembly.jar
      $env:SBT_OPTS = $env:SBT_OPTS + " -javaagent:" + $CLASS_MONKEY
      git clone --depth 1 https://github.com/ensime/ensime-server.git
      cp target/$CLASS_MONKEY ensime-server/
      cd ensime-server
      sbt test:compile it:compile
      sbt test
cache:
  - C:\sbt\
  - C:\Users\appveyor\.ivy2
  - C:\Users\appveyor\.coursier
on_failure:
  - appveyor PushArtifact -Path test.log
